#Q1
A <- c(18, 2, 20)
B <- c(22, 28, 10)
C <- c(20, 40, 40)
preferences <- data.frame(A, B, C)
cat("Preference Data:\n")
print(preferences)
cat("\nSample Covariance between B and C:\n")
print(cov(B, C))
cat("\nSample Covariance Matrix:\n")
print(cov(preferences))
cat("\nSample Correlation between B and C:\n")
print(cor(B, C))
cat("\nSample Correlation Matrix:\n")
print(cor(preferences))

#Q2
players <- c("Player A", "Player B", "Player C", "Player D","Player E", "Player F", "Player G", "Player H","Player I", "Player J", "Player K", "Player L","Player M", "Player N", "Player O")
points <- c(12, 15, 14, 10, 18, 20, 22, 13, 11, 35,16, 17, 19, 21, 23)
data <- data.frame(players, points)
cat("Player Scores:\n")
print(data)
boxplot(points,main = "Boxplot of Points Scored",ylab = "Points Scored",col = "lightblue")
cat("\nFive Number Summary:\n")
print(summary(points))
cat("\nOutliers:\n")
print(boxplot.stats(points)$out)

#Q3
library(rpart)
library(rpart.plot)
data <- data.frame(
  Age = c("young","young","middle","old","old","old","middle","young","young","old","middle","middle","old","young","middle"),
  Income = c("high","high","high","medium","low","low","low","medium","low","medium","medium","high","medium","medium","low"),
  Employment = c("employed","self-employed","employed","employed","unemployed","self-employed","unemployed","employed","unemployed","self-employed","employed","self-employed","unemployed","self-employed","employed"),
  Credit = c("good","average","good","good","poor","average","poor","average","poor","good","average","good","poor","average","poor"),
  Loan = c("yes","yes","yes","yes","no","no","no","yes","no","yes","yes","yes","no","yes","no")
)
data$Age <- factor(data$Age)
data$Income <- factor(data$Income)
data$Employment <- factor(data$Employment)
data$Credit <- factor(data$Credit)
data$Loan <- factor(data$Loan)
model <- rpart(Loan ~ Age + Income + Employment + Credit,data = data,method = "class",control = rpart.control(minsplit = 2, cp = 0))
print(model)
rpart.plot(model,main = "Decision Tree for Loan Approval")
predicted <- predict(model, data, type = "class")
cat("\nPredicted Loan Approval:\n")
print(predicted)
cat("\nConfusion Matrix:\n")
print(table(Actual = data$Loan,Predicted = predicted))
accuracy <- mean(predicted == data$Loan)
cat("\nAccuracy:\n")
print(accuracy)
cat("\nAccuracy Percentage:\n")
print(accuracy * 100)

#Q4
class_A <- c(76, 35, 47, 64, 95, 66, 89, 36, 84)
class_B <- c(51, 56, 84, 60, 59, 70, 63, 66, 50)
mean_A <- mean(class_A)
mean_B <- mean(class_B)
median_A <- median(class_A)
median_B <- median(class_B)
range_A <- max(class_A) - min(class_A)
range_B <- max(class_B) - min(class_B)
cat("Class A:\n")
cat("Mean =", mean_A, "\n")
cat("Median =", median_A, "\n")
cat("Range =", range_A, "\n")
cat("\nClass B:\n")
cat("Mean =", mean_B, "\n")
cat("Median =", median_B, "\n")
cat("Range =", range_B, "\n")
boxplot(class_A, class_B,names = c("Class A", "Class B"),main = "Comparison of Class A and Class B",ylab = "Exam Scores",col = c("lightblue", "lightgreen"))

#Q5
age <- c(23, 23, 27, 27, 39, 41, 47, 49, 50,52, 54, 54, 56, 57, 58, 58, 60, 61)
fat <- c(9.5, 26.5, 7.8, 17.8, 31.4, 25.9, 27.4, 27.2, 31.2,34.6, 42.5, 28.8, 33.4, 30.2, 34.1, 32.9, 41.2, 35.7)
data <- data.frame(age, fat)
cat("Age and Body Fat Data:\n")
print(data)
cat("\nAge Statistics:\n")
cat("Mean =", mean(age), "\n")
cat("Median =", median(age), "\n")
cat("Standard Deviation =", sd(age), "\n")
cat("\nBody Fat Statistics:\n")
cat("Mean =", mean(fat), "\n")
cat("Median =", median(fat), "\n")
cat("Standard Deviation =", sd(fat), "\n")
boxplot(age,main = "Boxplot of Age",ylab = "Age",col = "lightblue")
boxplot(fat,main = "Boxplot of Body Fat",ylab = "Body Fat (%)",col = "lightgreen")
plot(age, fat,main = "Scatter Plot: Age vs Body Fat",xlab = "Age",ylab = "Body Fat (%)",pch = 19)
abline(lm(fat ~ age), lwd = 2)
qqnorm(age,main = "Q-Q Plot of Age")
qqline(age, lwd = 2)
qqnorm(fat,main = "Q-Q Plot of Body Fat")
qqline(fat, lwd = 2)
cat("\nCorrelation between Age and Body Fat:\n")
print(cor(age, fat))